//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMATS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FileCategory()
        {
            this.FileDatas = new HashSet<FileData>();
        }
    
        public int FileCategoryId { get; set; }
        public string FileCategoryName { get; set; }
        public string FileCategoryDescription { get; set; }
        public string FileCategory_misc1 { get; set; }
        public string FileCategory_misc2 { get; set; }
        public string FileCategory_misc3 { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> DateLastModified { get; set; }
        public Nullable<int> Userid { get; set; }
        public Nullable<bool> Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileData> FileDatas { get; set; }
    }
}
