//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMATS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilePriority
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FilePriority()
        {
            this.FileDatas = new HashSet<FileData>();
        }
    
        public int FilePriorityId { get; set; }
        public string FilePriorityName { get; set; }
        public Nullable<decimal> FileWeight { get; set; }
        public Nullable<decimal> FilePriorityIntervalNotif { get; set; }
        public Nullable<decimal> FilePriorityIntervalAlert { get; set; }
        public Nullable<decimal> FilePriorityIntervalCrit { get; set; }
        public string FilePriority_misc1 { get; set; }
        public string FilePriority_misc2 { get; set; }
        public string FilePriority_misc3 { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileData> FileDatas { get; set; }
    }
}
