//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMATS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusHistory
    {
        public int StatusHistoryID { get; set; }
        public Nullable<int> FileDataId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public int AgentId { get; set; }
        public string Comments { get; set; }
        public bool IsCurrent { get; set; }
        public string StatusHistoryMisc1 { get; set; }
        public string StatusHistoryMisc2 { get; set; }
        public string StatusHistoryMisc3 { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual FileData FileData { get; set; }
    }
}
