//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMATS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agent()
        {
            this.FileDatas = new HashSet<FileData>();
        }
    
        public int AgentId { get; set; }
        public string AgentName { get; set; }
        public Nullable<int> AgentTypeID { get; set; }
        public string AgentEmployeeName { get; set; }
        public Nullable<int> AgentAccessLevelId { get; set; }
        public Nullable<long> AgentMobile { get; set; }
        public string AgentEmail { get; set; }
        public string AgentScanPref { get; set; }
        public string AgentSection { get; set; }
        public string AgentMisc1 { get; set; }
        public string AgentMisc2 { get; set; }
        public string AgentMisc3 { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual AgentAccessLevel AgentAccessLevel { get; set; }
        public virtual AgentType AgentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileData> FileDatas { get; set; }
    }
}
