//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FMATS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientCategory
    {
        public int ClientId { get; set; }
        public string ClientCategoryName { get; set; }
        public string ClientCategoryDescription { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> dateadded { get; set; }
        public Nullable<System.DateTime> dateLastModified { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
